services:
  backend:
    build:
      context: ./
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://postgres:taskapp@db:5432/taskapp
      - JWT_SECRET=secret
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    image: postgres:14
    container_name: taskapp-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=taskapp
      - POSTGRES_DB=taskapp
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
